### ISSUE TITLE
Website not found

### ISSUE THREAD

**Issue by jatin-pahuja** [Emisha-GITA/Demo-Portfolio-Website#139]
when i click the link in about it shows page not found.
![issue](https://user-images.githubusercontent.com/56190028/89010769-db54a200-d32c-11ea-9a63-6ddafa4dbf66.JPG)

**Comment by reetpriye** [comment]
The user has changed his/her username. So check at [this link]( https://emishacommunity.github.io/Demo-Portfolio-Website/).
